GET http://localhost:9080/forge/api/users
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

GET http://localhost:9080/forge/api/users/diana
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

GET http://localhost:9080/forge/api/avatars/cyryl
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

GET http://localhost:9080/forge/api/avatars/bob
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###


PUT http://localhost:9080/forge/api/avatars/cyryl
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic a2V2aW46dXNlcnVzZXI=

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg'

< /home/student/Pulpit/175840/Lab1_JEE/src/main/resources/avatars/avatar.jpg
--boundary--

###

DELETE http://localhost:9080/forge/api/avatars/cyryl
Authorization: Basic a2V2aW46dXNlcnVzZXI=


###

GET http://localhost:9080/forge/api/errands
Authorization: Basic a2V2aW46dXNlcnVzZXI=